//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_MessageContent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E_MessageContent()
        {
            this.E_MessageContentG_Individuals = new HashSet<E_MessageContentG_Individuals>();
        }
    
        public long E_MessageContent_Id { get; set; }
        public Nullable<long> E_Messages_Id { get; set; }
        public long E_Languages_Id { get; set; }
        public System.DateTime Created { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public bool Html { get; set; }
    
        public virtual E_Messages E_Messages { get; set; }
        public virtual G_Languages G_Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_MessageContentG_Individuals> E_MessageContentG_Individuals { get; set; }
    }
}
