//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class E_Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public E_Messages()
        {
            this.E_MessageContent = new HashSet<E_MessageContent>();
            this.E_MessagesR_Lists = new HashSet<E_MessagesR_Lists>();
        }
    
        public long E_Messages_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public System.DateTime Created { get; set; }
        public string FromEmail { get; set; }
        public Nullable<System.DateTime> SendAt { get; set; }
        public string Comment { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public bool Html { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_MessageContent> E_MessageContent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_MessagesR_Lists> E_MessagesR_Lists { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
