//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Bills()
        {
            this.G_Reminders = new HashSet<G_Reminders>();
        }
    
        public long G_Bills_Id { get; set; }
        public long G_Individuals_Id { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public long G_Countries_Id { get; set; }
        public decimal Amount { get; set; }
        public decimal SetUpFee { get; set; }
        public decimal HandlingFee { get; set; }
        public decimal Vat { get; set; }
        public decimal Adjustment { get; set; }
        public decimal ManualAdjustment { get; set; }
        public string ManualAdjustmentMotivation { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public System.DateTime Due { get; set; }
        public Nullable<decimal> AmountPayed { get; set; }
        public Nullable<System.DateTime> DatePayed { get; set; }
        public string Ocr { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public long G_PaymentMethods_Id { get; set; }
        public System.DateTime Created { get; set; }
        public bool BillingAccounted { get; set; }
        public bool PaymentsAccounted { get; set; }
    
        public virtual G_PaymentMethods G_PaymentMethods { get; set; }
        public virtual G_Individuals G_Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Reminders> G_Reminders { get; set; }
    }
}
