//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Cultures
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Cultures()
        {
            this.G_LocalizedTextTranslations = new HashSet<G_LocalizedTextTranslations>();
            this.M_Messages = new HashSet<M_Messages>();
            this.T_Translate = new HashSet<T_Translate>();
            this.T_Translated = new HashSet<T_Translated>();
        }
    
        public long G_Cultures_Id { get; set; }
        public string Culture { get; set; }
        public string Name { get; set; }
        public Nullable<long> G_Languages_Id { get; set; }
        public Nullable<long> G_Countries_Id { get; set; }
    
        public virtual G_Languages G_Languages { get; set; }
        public virtual G_Languages G_Languages1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_LocalizedTextTranslations> G_LocalizedTextTranslations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Messages> M_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Translate> T_Translate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Translated> T_Translated { get; set; }
    }
}
