//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_DocumentManagementTaxonomies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_DocumentManagementTaxonomies()
        {
            this.G_DocumentManagementTaxonomies1 = new HashSet<G_DocumentManagementTaxonomies>();
            this.G_DocumentManagementTaxonomiesG_ManagedDocuments = new HashSet<G_DocumentManagementTaxonomiesG_ManagedDocuments>();
        }
    
        public long G_DocumentManagementTaxonomies_Id { get; set; }
        public Nullable<long> ParentG_DocumentManagementTaxonomies_Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_DocumentManagementTaxonomies> G_DocumentManagementTaxonomies1 { get; set; }
        public virtual G_DocumentManagementTaxonomies G_DocumentManagementTaxonomies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_DocumentManagementTaxonomiesG_ManagedDocuments> G_DocumentManagementTaxonomiesG_ManagedDocuments { get; set; }
    }
}
