//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_FileExtensions
    {
        public long G_FileExtensions_Id { get; set; }
        public Nullable<long> G_MimeTypes_Id { get; set; }
        public string Extension { get; set; }
    
        public virtual G_MimeTypes G_MimeTypes { get; set; }
    }
}
