//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Forms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Forms()
        {
            this.G_SecurityGroupsG_Forms = new HashSet<G_SecurityGroupsG_Forms>();
        }
    
        public long G_Forms_Id { get; set; }
        public long G_Pages_Id { get; set; }
        public string Name { get; set; }
    
        public virtual G_Pages G_Pages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_SecurityGroupsG_Forms> G_SecurityGroupsG_Forms { get; set; }
    }
}
