//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ForumMessages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_ForumMessages()
        {
            this.G_ForumMessages_Tree = new HashSet<G_ForumMessages_Tree>();
            this.I_GesCaseReports = new HashSet<I_GesCaseReports>();
        }
    
        public long G_ForumMessages_Id { get; set; }
        public Nullable<long> ParentG_ForumMessages_Id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public Nullable<long> AuthorG_Users_Id { get; set; }
        public string Text { get; set; }
        public System.DateTime Modified { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_Users G_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ForumMessages_Tree> G_ForumMessages_Tree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReports> I_GesCaseReports { get; set; }
    }
}
