//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_LocalizedTexts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_LocalizedTexts()
        {
            this.G_LocalizedTextTranslations = new HashSet<G_LocalizedTextTranslations>();
        }
    
        public long G_LocalizedTexts_Id { get; set; }
        public string Key { get; set; }
        public bool C_New { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_LocalizedTextTranslations> G_LocalizedTextTranslations { get; set; }
    }
}
