//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ManagedDocuments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_ManagedDocuments()
        {
            this.G_DocumentManagementTaxonomiesG_ManagedDocuments = new HashSet<G_DocumentManagementTaxonomiesG_ManagedDocuments>();
            this.G_ManagedDocumentItems = new HashSet<G_ManagedDocumentItems>();
            this.G_ManagedDocumentsG_ManagedDocumentTaggs = new HashSet<G_ManagedDocumentsG_ManagedDocumentTaggs>();
            this.G_Uploads = new HashSet<G_Uploads>();
            this.G_Urls = new HashSet<G_Urls>();
            this.I_ControversialCompaniesI_ControversialActivites = new HashSet<I_ControversialCompaniesI_ControversialActivites>();
            this.I_Conventions = new HashSet<I_Conventions>();
            this.I_GesCaseReportReferences = new HashSet<I_GesCaseReportReferences>();
            this.I_GesCaseReportSources = new HashSet<I_GesCaseReportSources>();
            this.I_GesCaseReportSupplementaryReading = new HashSet<I_GesCaseReportSupplementaryReading>();
            this.I_ReportFiles = new HashSet<I_ReportFiles>();
            this.I_GesCaseReportsG_ManagedDocuments = new HashSet<I_GesCaseReportsG_ManagedDocuments>();
            this.I_GesCaseReports = new HashSet<I_GesCaseReports>();
        }
    
        public long G_ManagedDocuments_Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> G_ManagedDocumentApprovalStatuses_Id { get; set; }
        public Nullable<long> G_ManagedDocumentRiskLevels_Id { get; set; }
        public Nullable<long> G_DocumentManagementTaxonomies_Id { get; set; }
        public Nullable<long> G_ManagedDocumentServices_Id { get; set; }
        public Nullable<long> I_Msci_Id { get; set; }
        public Nullable<long> I_Ftse_Id { get; set; }
        public string DateText { get; set; }
        public string Source { get; set; }
        public string Keywords { get; set; }
        public string Comment { get; set; }
        public Nullable<long> NecI_Companies_Id { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_DocumentManagementTaxonomiesG_ManagedDocuments> G_DocumentManagementTaxonomiesG_ManagedDocuments { get; set; }
        public virtual G_ManagedDocumentApprovalStatuses G_ManagedDocumentApprovalStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocumentItems> G_ManagedDocumentItems { get; set; }
        public virtual G_ManagedDocumentRiskLevels G_ManagedDocumentRiskLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocumentsG_ManagedDocumentTaggs> G_ManagedDocumentsG_ManagedDocumentTaggs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Uploads> G_Uploads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Urls> G_Urls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialCompaniesI_ControversialActivites> I_ControversialCompaniesI_ControversialActivites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Conventions> I_Conventions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportReferences> I_GesCaseReportReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportSources> I_GesCaseReportSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportSupplementaryReading> I_GesCaseReportSupplementaryReading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ReportFiles> I_ReportFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsG_ManagedDocuments> I_GesCaseReportsG_ManagedDocuments { get; set; }
        public virtual I_Companies I_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReports> I_GesCaseReports { get; set; }
    }
}
