//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ManagedDocumentTaggs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_ManagedDocumentTaggs()
        {
            this.G_ManagedDocumentsG_ManagedDocumentTaggs = new HashSet<G_ManagedDocumentsG_ManagedDocumentTaggs>();
        }
    
        public long G_ManagedDocumentTaggs_Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocumentsG_ManagedDocumentTaggs> G_ManagedDocumentsG_ManagedDocumentTaggs { get; set; }
    }
}
