//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ManagedDocumentsG_ManagedDocumentTaggs
    {
        public long G_ManagedDocumentsG_ManagedDocumentTaggs_Id { get; set; }
        public long G_ManagedDocuments_Id { get; set; }
        public long G_ManagedDocumentTaggs_Id { get; set; }
        public string Value { get; set; }
    
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual G_ManagedDocumentTaggs G_ManagedDocumentTaggs { get; set; }
    }
}
