//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ManagedDocumentItems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_ManagedDocumentItems()
        {
            this.G_ManagedDocumentItems1 = new HashSet<G_ManagedDocumentItems>();
        }
    
        public long G_ManagedDocumentItems_Id { get; set; }
        public Nullable<long> ParentG_ManagedDocumentItems_Id { get; set; }
        public long G_ManagedDocuments_Id { get; set; }
        public Nullable<long> G_Uploads_Id { get; set; }
        public Nullable<long> G_Texts_Id { get; set; }
        public Nullable<long> G_Urls_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocumentItems> G_ManagedDocumentItems1 { get; set; }
        public virtual G_ManagedDocumentItems G_ManagedDocumentItems2 { get; set; }
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual G_Uploads G_Uploads { get; set; }
        public virtual G_Urls G_Urls { get; set; }
    }
}
