//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_MultiLangDescriptions
    {
        public long G_MultiLangDescriptions_Id { get; set; }
        public long G_Languages_Id { get; set; }
        public string Description { get; set; }
    
        public virtual G_Languages G_Languages { get; set; }
    }
}
