//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_News
    {
        public long G_News_Id { get; set; }
        public long G_NewsTypes_Id { get; set; }
        public Nullable<long> G_NewsCategories_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Published { get; set; }
        public Nullable<long> G_ManagedDocuments_Id { get; set; }
        public System.DateTime Created { get; set; }
    }
}
