//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Organizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Organizations()
        {
            this.E_Messages = new HashSet<E_Messages>();
            this.G_Individuals = new HashSet<G_Individuals>();
            this.I_CompaniesG_Organizations = new HashSet<I_CompaniesG_Organizations>();
            this.R_Lists = new HashSet<R_Lists>();
            this.G_Organizations1 = new HashSet<G_Organizations>();
            this.G_Organizations_GesDocument = new HashSet<G_Organizations_GesDocument>();
            this.R_ListsG_Organizations = new HashSet<R_ListsG_Organizations>();
            this.G_OrganizationsG_Services = new HashSet<G_OrganizationsG_Services>();
            this.G_WebServiceUsers = new HashSet<G_WebServiceUsers>();
            this.I_ActivityForms = new HashSet<I_ActivityForms>();
            this.I_Companies1 = new HashSet<I_Companies>();
            this.I_PortfoliosG_Organizations = new HashSet<I_PortfoliosG_Organizations>();
            this.T_Activites = new HashSet<T_Activites>();
            this.T_Projects = new HashSet<T_Projects>();
            this.T_Translate = new HashSet<T_Translate>();
        }
    
        public long G_Organizations_Id { get; set; }
        public Nullable<long> OwnerG_Organizations_Id { get; set; }
        public Nullable<long> G_Industries_Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public string LicenseKey { get; set; }
        public string Name { get; set; }
        public string OrgNr { get; set; }
        public string Domain { get; set; }
        public string WebsiteUrl { get; set; }
        public Nullable<bool> WebsiteExists { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public Nullable<long> G_Countries_Id { get; set; }
        public Nullable<long> G_Languages_Id { get; set; }
        public string BillingAddress1 { get; set; }
        public string BillingAddress2 { get; set; }
        public string BillingAddress3 { get; set; }
        public string BillingPostalCode { get; set; }
        public string BillingCity { get; set; }
        public Nullable<long> BillingG_Countries_Id { get; set; }
        public Nullable<long> G_PaymentMethods_Id { get; set; }
        public string PostgiroNumber { get; set; }
        public string BankgiroNumber { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string LogoUrl { get; set; }
        public string Comment { get; set; }
        public string OurApproach { get; set; }
        public Nullable<long> G_SaleStates_Id { get; set; }
        public int CreditPaymentTerms { get; set; }
        public Nullable<long> G_SalesRatings_Id { get; set; }
        public Nullable<int> Employees { get; set; }
        public string Members { get; set; }
        public Nullable<decimal> TotalAssets { get; set; }
        public string Equity { get; set; }
        public string Property { get; set; }
        public string Fi { get; set; }
        public string SalesInterest { get; set; }
        public Nullable<System.DateTime> SalesFirstContact { get; set; }
        public Nullable<System.DateTime> SalesLastContact { get; set; }
        public Nullable<System.DateTime> SalesNextContact { get; set; }
        public string SalesMeetingReport { get; set; }
        public string SalesComment { get; set; }
        public string ReferredBy { get; set; }
        public string DeliveryDate { get; set; }
        public bool Customer { get; set; }
        public Nullable<long> G_OrganizationsI_ClientStatuses_Id { get; set; }
        public Nullable<long> I_ClientProgressStatuses_Id { get; set; }
        public Nullable<int> FreeHours { get; set; }
        public Nullable<decimal> StandardPrice { get; set; }
        public Nullable<long> I_Companies_Id { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_Messages> E_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Individuals> G_Individuals { get; set; }
        public virtual G_Industries G_Industries { get; set; }
        public virtual G_Languages G_Languages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesG_Organizations> I_CompaniesG_Organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_Lists> R_Lists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Organizations> G_Organizations1 { get; set; }
        public virtual G_Organizations G_Organizations2 { get; set; }
        public virtual G_PaymentMethods G_PaymentMethods { get; set; }
        public virtual G_SalesRatings G_SalesRatings { get; set; }
        public virtual G_SaleStates G_SaleStates { get; set; }
        public virtual G_Users G_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Organizations_GesDocument> G_Organizations_GesDocument { get; set; }
        public virtual I_Companies I_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ListsG_Organizations> R_ListsG_Organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_OrganizationsG_Services> G_OrganizationsG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_WebServiceUsers> G_WebServiceUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ActivityForms> I_ActivityForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Companies> I_Companies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfoliosG_Organizations> I_PortfoliosG_Organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Activites> T_Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Projects> T_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Translate> T_Translate { get; set; }
    }
}
