//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_OrganizationsI_ClientStatuses
    {
        public long G_OrganizationsI_ClientStatuses_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public long I_ClientStatuses_Id { get; set; }
        public bool Done { get; set; }
        public Nullable<System.DateTime> DateChanged { get; set; }
        public Nullable<long> G_ManagedDocuments_Id { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    }
}
