//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_OrganizationsG_Services
    {
        public long G_OrganizationsG_Services_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public long G_Services_Id { get; set; }
        public Nullable<long> G_ManagedDocuments_Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public Nullable<System.DateTime> DemoEnd { get; set; }
        public long G_ServiceStates_Id { get; set; }
        public bool TermsAccepted { get; set; }
        public string TermsAcceptedByIp { get; set; }
        public bool W_SuperFilter { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Reporting { get; set; }
        public string Comment { get; set; }
    
        public virtual G_ServiceStates G_ServiceStates { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual G_Services G_Services { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
