//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_QualityPolicies
    {
        public long G_QualityPolicies_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> MaxDaysEmpty { get; set; }
        public Nullable<int> ReviewInterval { get; set; }
        public System.DateTime Created { get; set; }
    }
}
