//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ReportingTemplatesG_ReportingModules
    {
        public long G_ReportingTemplatesG_ReportingModules_Id { get; set; }
        public long G_ReportingTemplates_Id { get; set; }
        public long G_ReportingPageModules_Id { get; set; }
        public Nullable<long> TemplateG_Uploads_Id { get; set; }
    
        public virtual G_ReportingPageModules G_ReportingPageModules { get; set; }
        public virtual G_ReportingTemplates G_ReportingTemplates { get; set; }
        public virtual G_Uploads G_Uploads { get; set; }
    }
}
