//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Services()
        {
            this.G_IndividualsG_Services = new HashSet<G_IndividualsG_Services>();
            this.G_OrganizationsG_Services = new HashSet<G_OrganizationsG_Services>();
            this.I_CompaniesG_Services = new HashSet<I_CompaniesG_Services>();
            this.I_PortfoliosG_OrganizationsG_Services = new HashSet<I_PortfoliosG_OrganizationsG_Services>();
        }
    
        public long G_Services_Id { get; set; }
        public Nullable<int> Sort { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool ShowInNavigation { get; set; }
        public bool ShowInClient { get; set; }
        public string ReportLetter { get; set; }
        public Nullable<long> I_EngagementTypes_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_IndividualsG_Services> G_IndividualsG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_OrganizationsG_Services> G_OrganizationsG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesG_Services> I_CompaniesG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfoliosG_OrganizationsG_Services> I_PortfoliosG_OrganizationsG_Services { get; set; }
    }
}
