//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SecurityGroupsG_Forms
    {
        public long G_SecurityGroupsG_Forms_Id { get; set; }
        public long G_SecurityGroups_Id { get; set; }
        public long G_Forms_Id { get; set; }
        public bool AllowRead { get; set; }
        public bool AllowInsert { get; set; }
        public bool AllowUpdate { get; set; }
        public bool AllowDelete { get; set; }
    
        public virtual G_Forms G_Forms { get; set; }
        public virtual G_SecurityGroups G_SecurityGroups { get; set; }
    }
}
