//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_SecurityGroups
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_SecurityGroups()
        {
            this.G_SecurityGroupsG_Forms = new HashSet<G_SecurityGroupsG_Forms>();
            this.G_SecurityGroupsG_Pages = new HashSet<G_SecurityGroupsG_Pages>();
            this.G_SecurityGroupsG_SecurityRights = new HashSet<G_SecurityGroupsG_SecurityRights>();
            this.G_UsersG_SecurityGroups = new HashSet<G_UsersG_SecurityGroups>();
        }
    
        public long G_SecurityGroups_Id { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_SecurityGroupsG_Forms> G_SecurityGroupsG_Forms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_SecurityGroupsG_Pages> G_SecurityGroupsG_Pages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_SecurityGroupsG_SecurityRights> G_SecurityGroupsG_SecurityRights { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_UsersG_SecurityGroups> G_UsersG_SecurityGroups { get; set; }
    }
}
