//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ServiceStates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_ServiceStates()
        {
            this.G_OrganizationsG_Services = new HashSet<G_OrganizationsG_Services>();
        }
    
        public long G_ServiceStates_Id { get; set; }
        public long G_IntNameIds_Id { get; set; }
    
        public virtual G_IntNameIds G_IntNameIds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_OrganizationsG_Services> G_OrganizationsG_Services { get; set; }
    }
}
