//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_TimeZones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_TimeZones()
        {
            this.G_Individuals = new HashSet<G_Individuals>();
        }
    
        public long G_TimeZones_Id { get; set; }
        public string Name { get; set; }
        public string StandardName { get; set; }
        public string DaylightName { get; set; }
        public Nullable<int> Bias { get; set; }
        public Nullable<int> DaylightBias { get; set; }
        public Nullable<short> StandardMonth { get; set; }
        public Nullable<short> StandardDay { get; set; }
        public Nullable<short> StandardDayOfWeek { get; set; }
        public Nullable<short> StandardHour { get; set; }
        public Nullable<short> DaylightMonth { get; set; }
        public Nullable<short> DaylightDay { get; set; }
        public Nullable<short> DaylightDayOfWeek { get; set; }
        public Nullable<short> DaylightHour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Individuals> G_Individuals { get; set; }
    }
}
