//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Uploads
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Uploads()
        {
            this.G_ManagedDocumentItems = new HashSet<G_ManagedDocumentItems>();
            this.G_ReportingTemplatesG_ReportingModules = new HashSet<G_ReportingTemplatesG_ReportingModules>();
            this.G_Uploads1 = new HashSet<G_Uploads>();
            this.I_Scores = new HashSet<I_Scores>();
        }
    
        public long G_Uploads_Id { get; set; }
        public Nullable<long> ParentG_Uploads_Id { get; set; }
        public Nullable<long> G_ManagedDocuments_Id { get; set; }
        public string FileName { get; set; }
        public Nullable<long> G_MimeTypes_Id { get; set; }
        public string OriginalFileName { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocumentItems> G_ManagedDocumentItems { get; set; }
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual G_MimeTypes G_MimeTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ReportingTemplatesG_ReportingModules> G_ReportingTemplatesG_ReportingModules { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Uploads> G_Uploads1 { get; set; }
        public virtual G_Uploads G_Uploads2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Scores> I_Scores { get; set; }
    }
}
