//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public G_Users()
        {
            this.G_ForumMessages = new HashSet<G_ForumMessages>();
            this.G_Individuals = new HashSet<G_Individuals>();
            this.G_OrganizationsG_Services = new HashSet<G_OrganizationsG_Services>();
            this.I_Scores = new HashSet<I_Scores>();
            this.G_Users1 = new HashSet<G_Users>();
            this.G_UsersG_SecurityGroups = new HashSet<G_UsersG_SecurityGroups>();
            this.I_CompaniesI_ManagementSystems = new HashSet<I_CompaniesI_ManagementSystems>();
            this.I_ControversialCompanies = new HashSet<I_ControversialCompanies>();
            this.I_ControversialCompanies1 = new HashSet<I_ControversialCompanies>();
            this.I_ControversialCompaniesI_ControversialActivites = new HashSet<I_ControversialCompaniesI_ControversialActivites>();
            this.I_EngagementProfiles = new HashSet<I_EngagementProfiles>();
            this.I_IndividualListsG_Individuals = new HashSet<I_IndividualListsG_Individuals>();
            this.I_Nas = new HashSet<I_Nas>();
            this.I_Questions = new HashSet<I_Questions>();
            this.I_RiskCompanies = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies1 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies2 = new HashSet<I_RiskCompanies>();
            this.I_Themes = new HashSet<I_Themes>();
            this.L_UsersUsers = new HashSet<L_UsersUsers>();
            this.M_Messages = new HashSet<M_Messages>();
            this.T_Activites = new HashSet<T_Activites>();
            this.T_ActivityTypes = new HashSet<T_ActivityTypes>();
            this.T_Projects = new HashSet<T_Projects>();
            this.I_Companies = new HashSet<I_Companies>();
            this.I_Companies1 = new HashSet<I_Companies>();
            this.G_Organizations = new HashSet<G_Organizations>();
            this.I_NaArticles = new HashSet<I_NaArticles>();
            this.I_GesCaseReports = new HashSet<I_GesCaseReports>();
            this.I_GesCaseReports1 = new HashSet<I_GesCaseReports>();
        }
    
        public long G_Users_Id { get; set; }
        public long G_Individuals_Id { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLogIn { get; set; }
        public Nullable<System.DateTime> LastLogIn2 { get; set; }
        public string LastLogInIp { get; set; }
        public int LogInCount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ForumMessages> G_ForumMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Individuals> G_Individuals { get; set; }
        public virtual G_Individuals G_Individuals1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_OrganizationsG_Services> G_OrganizationsG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Scores> I_Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Users> G_Users1 { get; set; }
        public virtual G_Users G_Users2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_UsersG_SecurityGroups> G_UsersG_SecurityGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesI_ManagementSystems> I_CompaniesI_ManagementSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialCompanies> I_ControversialCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialCompanies> I_ControversialCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialCompaniesI_ControversialActivites> I_ControversialCompaniesI_ControversialActivites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementProfiles> I_EngagementProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_IndividualListsG_Individuals> I_IndividualListsG_Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Nas> I_Nas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Questions> I_Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Themes> I_Themes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<L_UsersUsers> L_UsersUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_Messages> M_Messages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Activites> T_Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ActivityTypes> T_ActivityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Projects> T_Projects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Companies> I_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Companies> I_Companies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Organizations> G_Organizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_NaArticles> I_NaArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReports> I_GesCaseReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReports> I_GesCaseReports1 { get; set; }
    }
}
