//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_WebServiceUsers
    {
        public long G_WebServiceUsers_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public string Name { get; set; }
        public string LicenseKey { get; set; }
        public bool Enabled { get; set; }
        public int AccessCount { get; set; }
        public Nullable<System.DateTime> LastAccess { get; set; }
        public string LastAccessIp { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_WebServiceUsers G_WebServiceUsers1 { get; set; }
        public virtual G_WebServiceUsers G_WebServiceUsers2 { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
