//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesAnnouncement
    {
        public System.Guid GesAnnouncementId { get; set; }
        public string Title { get; set; }
        public string LinkTitle { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> AnnouncementDate { get; set; }
    }
}
