//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesCaseReports_Audit_Details
    {
        public System.Guid GesCaseReports_Audit_Details1 { get; set; }
        public System.Guid GesCaseReports_Audit_GesCaseReports_Audit_Id { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string AuditDataState { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditDatetime { get; set; }
    
        public virtual GesCaseReports_Audit GesCaseReports_Audit { get; set; }
    }
}
