//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesCaseReports_Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesCaseReports_Audit()
        {
            this.GesCaseReports_Audit_Details = new HashSet<GesCaseReports_Audit_Details>();
        }
    
        public System.Guid GesCaseReports_Audit_Id { get; set; }
        public int I_GesCaseReports_Id { get; set; }
        public string AuditUser { get; set; }
        public string AuditDMLAction { get; set; }
        public System.DateTime AuditDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCaseReports_Audit_Details> GesCaseReports_Audit_Details { get; set; }
    }
}
