//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesCompanyProfiles
    {
        public System.Guid GesCompanyProfileId { get; set; }
        public string Isin { get; set; }
        public Nullable<bool> IsPrime { get; set; }
        public string Grade { get; set; }
        public string PrimeThreshold { get; set; }
        public string KeyIssues { get; set; }
        public string Distribution { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
    
        public virtual GesDocument GesDocument { get; set; }
    }
}
