//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesCaseProfileTemplates
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesCaseProfileTemplates()
        {
            this.GesCaseProfileInvisibleEntities = new HashSet<GesCaseProfileInvisibleEntities>();
        }
    
        public System.Guid GesCaseProfileTemplates_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> I_EngagementTypes_Id { get; set; }
        public Nullable<long> I_GesCaseReportStatuses_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> ModifiedByG_Users_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCaseProfileInvisibleEntities> GesCaseProfileInvisibleEntities { get; set; }
        public virtual I_GesCaseReportStatuses I_GesCaseReportStatuses { get; set; }
        public virtual I_EngagementTypes I_EngagementTypes { get; set; }
    }
}
