//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesCaseProfileInvisibleEntities
    {
        public System.Guid GesCaseProfileInvisibleEntity_Id { get; set; }
        public System.Guid GesCaseProfileTemplates_Id { get; set; }
        public System.Guid GesCaseProfileEntity_Id { get; set; }
        public Nullable<int> InVisibleType { get; set; }
    
        public virtual I_GesCaseProfileEntities I_GesCaseProfileEntities { get; set; }
        public virtual GesCaseProfileTemplates GesCaseProfileTemplates { get; set; }
    }
}
