//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesDocument()
        {
            this.G_Organizations_GesDocument = new HashSet<G_Organizations_GesDocument>();
            this.GesCompanyProfiles = new HashSet<GesCompanyProfiles>();
            this.Sdg = new HashSet<Sdg>();
            this.I_EngagementTypes_GesDocument = new HashSet<I_EngagementTypes_GesDocument>();
        }
    
        public System.Guid DocumentId { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public Nullable<long> GesDocumentServiceId { get; set; }
        public string Source { get; set; }
        public string Metadata01 { get; set; }
        public string Metadata02 { get; set; }
        public string Metadata03 { get; set; }
        public string Comment { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public string HashCodeDocument { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Organizations_GesDocument> G_Organizations_GesDocument { get; set; }
        public virtual GesDocumentService GesDocumentService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCompanyProfiles> GesCompanyProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sdg> Sdg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementTypes_GesDocument> I_EngagementTypes_GesDocument { get; set; }
    }
}
