//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesEventCalendarUserAccept
    {
        public System.Guid GesEventCalendarUserAcceptId { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public long I_CalenderEvents_Id { get; set; }
        public Nullable<bool> IsSentUpdate { get; set; }
        public Nullable<System.DateTime> UpdateSentDate { get; set; }
    
        public virtual I_CalenderEvents I_CalenderEvents { get; set; }
    }
}
