//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesUNGPAssessmentScores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesUNGPAssessmentScores()
        {
            this.GesUNGPAssessmentForm = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm1 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm2 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm3 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm4 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm5 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm6 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm7 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm8 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm9 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm10 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm11 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm12 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm13 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm14 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm15 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm16 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm17 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm18 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm19 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm20 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm21 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm22 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm23 = new HashSet<GesUNGPAssessmentForm>();
            this.GesUNGPAssessmentForm24 = new HashSet<GesUNGPAssessmentForm>();
        }
    
        public System.Guid GesUNGPAssessmentScoresId { get; set; }
        public string Name { get; set; }
        public string ScoreType { get; set; }
        public double Score { get; set; }
        public Nullable<int> Order { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm13 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm14 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm15 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm16 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm17 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm18 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm19 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm21 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm22 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm23 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm24 { get; set; }
    }
}
