//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesUNGPAssessmentFormResource_Audit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesUNGPAssessmentFormResource_Audit()
        {
            this.GesUNGPAssessmentFormResource_Audit_Details = new HashSet<GesUNGPAssessmentFormResource_Audit_Details>();
        }
    
        public System.Guid GesUNGPAssessmentFormResource_Audit_Id { get; set; }
        public System.Guid GesUNGPAssessmentFormId { get; set; }
        public System.Guid GesUNGPAssessmentFormResourcesId { get; set; }
        public string AuditDMLAction { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentFormResource_Audit_Details> GesUNGPAssessmentFormResource_Audit_Details { get; set; }
    }
}
