//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesUNGPAssessmentForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GesUNGPAssessmentForm()
        {
            this.GesUNGPAssessmentFormResources = new HashSet<GesUNGPAssessmentFormResources>();
        }
    
        public System.Guid GesUNGPAssessmentFormId { get; set; }
        public long I_GesCaseReports_Id { get; set; }
        public Nullable<System.Guid> TheExtentOfHarmesScoreId { get; set; }
        public string TheExtentOfHarmesScoreComment { get; set; }
        public Nullable<System.Guid> TheNumberOfPeopleAffectedScoreId { get; set; }
        public string TheNumberOfPeopleAffectedScoreComment { get; set; }
        public Nullable<System.Guid> OverSeveralYearsScoreId { get; set; }
        public string OverSeveralYearsScoreComment { get; set; }
        public Nullable<System.Guid> SeveralLocationsScoreId { get; set; }
        public string SeveralLocationsScoreComment { get; set; }
        public Nullable<System.Guid> IsViolationScoreId { get; set; }
        public string IsViolationScoreComment { get; set; }
        public Nullable<System.Guid> GesConfirmedViolationScoreId { get; set; }
        public string GesConfirmedViolationScoreComment { get; set; }
        public Nullable<double> SalientHumanRightsPotentialViolationTotalScore { get; set; }
        public string GesCommentSalientHumanRight { get; set; }
        public Nullable<System.Guid> HumanRightsPolicyPubliclyDisclosedAddScoreId { get; set; }
        public string HumanRightsPolicyPubliclyDisclosed { get; set; }
        public Nullable<System.Guid> HumanRightsPolicyCommunicatedScoreId { get; set; }
        public string HumanRightsPolicyCommunicated { get; set; }
        public Nullable<System.Guid> HumanRightsPolicyStipulatesScoreId { get; set; }
        public string HumanRightsPolicyStipulates { get; set; }
        public Nullable<System.Guid> HumanRightsPolicyApprovedScoreId { get; set; }
        public string HumanRightsPolicyApproved { get; set; }
        public Nullable<double> HumanRightsPolicyTotalScore { get; set; }
        public Nullable<System.Guid> GovernanceCommitmentScoreId { get; set; }
        public string GovernanceCommitment { get; set; }
        public Nullable<System.Guid> GovernanceExamplesScoreId { get; set; }
        public string GovernanceExamples { get; set; }
        public Nullable<System.Guid> GovernanceClearDivisionScoreId { get; set; }
        public string GovernanceClearDivision { get; set; }
        public string BusinessPartners { get; set; }
        public Nullable<System.Guid> BusinessPartnersAddScoreId { get; set; }
        public Nullable<System.Guid> IdentificationAndCommitmentScoreId { get; set; }
        public string IdentificationAndCommitment { get; set; }
        public string StakeholderEngagement { get; set; }
        public Nullable<System.Guid> StakeholderEngagementAddScoreId { get; set; }
        public string HumanRightsTraining { get; set; }
        public Nullable<System.Guid> HumanRightsTrainingScoreId { get; set; }
        public Nullable<double> TotalScoreForHumanRightsDueDiligence { get; set; }
        public Nullable<System.Guid> RemedyProcessInPlaceScoreId { get; set; }
        public string RemedyProcessInPlace { get; set; }
        public Nullable<System.Guid> GrievanceMechanismHasOperationalLevelScoreId { get; set; }
        public string GrievanceMechanismHasOperationalLevel { get; set; }
        public Nullable<System.Guid> GrievanceMechanismExistenceOfOperationalLevelScoreId { get; set; }
        public string GrievanceMechanismExistenceOfOperationalLevel { get; set; }
        public Nullable<System.Guid> GrievanceMechanismClearProcessScoreId { get; set; }
        public string GrievanceMechanismClearProcess { get; set; }
        public Nullable<System.Guid> GrievanceMechanismRightsNormsScoreId { get; set; }
        public string GrievanceMechanismRightsNorms { get; set; }
        public Nullable<System.Guid> GrievanceMechanismFilingGrievanceScoreId { get; set; }
        public string GrievanceMechanismFilingGrievance { get; set; }
        public Nullable<System.Guid> GrievanceMechanismReoccurringGrievancesScoreId { get; set; }
        public string GrievanceMechanismReoccurringGrievances { get; set; }
        public Nullable<System.Guid> GrievanceMechanismFormatAndProcesseScoreId { get; set; }
        public string GrievanceMechanismFormatAndProcesse { get; set; }
        public Nullable<double> TotalScoreForRemediationOfAdverseHumanRightsImpacts { get; set; }
        public string GesCommentCompanyPreparedness { get; set; }
        public Nullable<double> TotalScoreForCompanyPreparedness { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentFormResources> GesUNGPAssessmentFormResources { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores1 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores2 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores3 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores4 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores5 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores6 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores7 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores8 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores9 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores10 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores11 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores12 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores13 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores14 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores15 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores16 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores17 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores18 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores19 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores20 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores21 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores22 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores23 { get; set; }
        public virtual GesUNGPAssessmentScores GesUNGPAssessmentScores24 { get; set; }
        public virtual I_GesCaseReports I_GesCaseReports { get; set; }
    }
}
