//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class GesUNGPAssessmentFormResource_Audit_Details
    {
        public System.Guid GesUNGPAssessmentFormResource_Audit_Details_Id { get; set; }
        public System.Guid GesUNGPAssessmentFormResource_Audit_Id { get; set; }
        public string ColumnName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public string AuditDataState { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDatetime { get; set; }
        public string ColumnNameDescription { get; set; }
    
        public virtual GesUNGPAssessmentFormResource_Audit GesUNGPAssessmentFormResource_Audit { get; set; }
    }
}
