//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ActivityForms
    {
        public long I_ActivityForms_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public long I_GesCaseReports_Id { get; set; }
        public Nullable<bool> Ownership { get; set; }
        public Nullable<int> Shares { get; set; }
        public Nullable<System.DateTime> AsOf { get; set; }
        public Nullable<bool> HoldingsThroughExternalFunds { get; set; }
        public Nullable<bool> FixedIncomeHoldings { get; set; }
        public Nullable<long> I_EngagementActivityOptions_Id { get; set; }
        public Nullable<bool> SignLetters { get; set; }
        public Nullable<bool> ParticipateInConferenceCalls { get; set; }
        public Nullable<bool> ParticipateInLiveMeetings { get; set; }
        public Nullable<bool> QuestionsToAgms { get; set; }
        public Nullable<bool> ClearinghouseActions { get; set; }
        public Nullable<bool> CollaborativeActions { get; set; }
        public Nullable<bool> FileResolutions { get; set; }
        public string Suggestions { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual I_EngagementActivityOptions I_EngagementActivityOptions { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
        public virtual I_GesCaseReports I_GesCaseReports { get; set; }
    }
}
