//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_CharScores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_CharScores()
        {
            this.I_HrCommunityRatingsConversionTable = new HashSet<I_HrCommunityRatingsConversionTable>();
            this.I_HrEmployeesRatingsConversionTable = new HashSet<I_HrEmployeesRatingsConversionTable>();
            this.I_HrRatingsConversionTable = new HashSet<I_HrRatingsConversionTable>();
            this.I_HrSuppliersRatingsConversionTable = new HashSet<I_HrSuppliersRatingsConversionTable>();
            this.I_HrTotalRatingsConversionTable = new HashSet<I_HrTotalRatingsConversionTable>();
            this.I_QuestionsByRisk = new HashSet<I_QuestionsByRisk>();
            this.I_RiskCompanies = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies1 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies2 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies3 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies4 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies5 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies6 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies7 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompanies8 = new HashSet<I_RiskCompanies>();
            this.I_RiskCompaniesStatistics = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics1 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics2 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics3 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics4 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics5 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics6 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics7 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics8 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics9 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics10 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics11 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskCompaniesStatistics12 = new HashSet<I_RiskCompaniesStatistics>();
            this.I_RiskStatistics = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics1 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics2 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics3 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics4 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics5 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics6 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics7 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics8 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics9 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics10 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics11 = new HashSet<I_RiskStatistics>();
            this.I_RiskStatistics12 = new HashSet<I_RiskStatistics>();
        }
    
        public long I_CharScores_Id { get; set; }
        public string Name { get; set; }
        public string LowerCaseName { get; set; }
        public Nullable<float> Score { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_HrCommunityRatingsConversionTable> I_HrCommunityRatingsConversionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_HrEmployeesRatingsConversionTable> I_HrEmployeesRatingsConversionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_HrRatingsConversionTable> I_HrRatingsConversionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_HrSuppliersRatingsConversionTable> I_HrSuppliersRatingsConversionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_HrTotalRatingsConversionTable> I_HrTotalRatingsConversionTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_QuestionsByRisk> I_QuestionsByRisk { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics12 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics6 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics7 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics8 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics9 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskStatistics> I_RiskStatistics12 { get; set; }
    }
}
