//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Conventions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Conventions()
        {
            this.I_ConventionSignatories = new HashSet<I_ConventionSignatories>();
            this.I_GesCaseReportsI_Conventions = new HashSet<I_GesCaseReportsI_Conventions>();
        }
    
        public long I_Conventions_Id { get; set; }
        public Nullable<long> I_ConventionCategories_Id { get; set; }
        public string Source { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Text { get; set; }
        public string Type { get; set; }
        public string Background { get; set; }
        public string Guidelines { get; set; }
        public string Purpose { get; set; }
        public string Administration { get; set; }
        public string GesCriteria { get; set; }
        public string GesScope { get; set; }
        public string GesRiskIndustry { get; set; }
        public string ManagementSystems { get; set; }
        public string Links { get; set; }
        public Nullable<long> G_ManagedDocuments_Id { get; set; }
    
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual I_ConventionCategories I_ConventionCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ConventionSignatories> I_ConventionSignatories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_Conventions> I_GesCaseReportsI_Conventions { get; set; }
    }
}
