//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_CompaniesI_ManagementSystems
    {
        public long I_CompaniesI_ManagementSystems_Id { get; set; }
        public long I_Companies_Id { get; set; }
        public long I_ManagementSystems_Id { get; set; }
        public bool Certification { get; set; }
        public Nullable<int> Coverage { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_Users G_Users { get; set; }
        public virtual I_ManagementSystems I_ManagementSystems { get; set; }
        public virtual I_Companies I_Companies { get; set; }
    }
}
