//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_CompaniesG_Services
    {
        public long I_CompaniesG_Services_Id { get; set; }
        public Nullable<long> I_Companies_Id { get; set; }
        public long G_Services_Id { get; set; }
    
        public virtual G_Services G_Services { get; set; }
        public virtual I_Companies I_Companies { get; set; }
    }
}
