//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialComments
    {
        public long I_ControversialComments_Id { get; set; }
        public long I_ControversialCompanies_Id { get; set; }
        public Nullable<long> I_ControversialActivites_Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual I_ControversialActivites I_ControversialActivites { get; set; }
        public virtual I_ControversialCompanies I_ControversialCompanies { get; set; }
    }
}
