//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_CompanyListTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_CompanyListTypes()
        {
            this.I_CompaniesI_CompanyListTypes = new HashSet<I_CompaniesI_CompanyListTypes>();
            this.I_CompaniesImport = new HashSet<I_CompaniesImport>();
            this.I_PortfolioCompaniesImport = new HashSet<I_PortfolioCompaniesImport>();
        }
    
        public long I_CompanyListTypes_Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesI_CompanyListTypes> I_CompaniesI_CompanyListTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesImport> I_CompaniesImport { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfolioCompaniesImport> I_PortfolioCompaniesImport { get; set; }
    }
}
