//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialScreening
    {
        public long I_ControversialScreening_Id { get; set; }
        public long I_ControversialCompanies_Id { get; set; }
        public long I_ControversialActivites_Id { get; set; }
        public Nullable<System.DateTime> Screened { get; set; }
        public System.DateTime Created { get; set; }
    }
}
