//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialActivitesGroups
    {
        public long I_ControversialActivitesGroups_Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
