//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Companies()
        {
            this.G_ManagedDocuments = new HashSet<G_ManagedDocuments>();
            this.I_CompaniesG_Services = new HashSet<I_CompaniesG_Services>();
            this.I_RiskCompanies = new HashSet<I_RiskCompanies>();
            this.I_Companies1 = new HashSet<I_Companies>();
            this.I_CompaniesI_CompanyListTypes = new HashSet<I_CompaniesI_CompanyListTypes>();
            this.I_CompaniesI_ManagementSystems = new HashSet<I_CompaniesI_ManagementSystems>();
            this.I_EngagementDiscussionPoints = new HashSet<I_EngagementDiscussionPoints>();
            this.I_EngagementGap = new HashSet<I_EngagementGap>();
            this.I_EngagementGoal = new HashSet<I_EngagementGoal>();
            this.I_EngagementIssuesInfo = new HashSet<I_EngagementIssuesInfo>();
            this.I_EngagementOtherStakeholderViews = new HashSet<I_EngagementOtherStakeholderViews>();
            this.I_EngagementProfiles = new HashSet<I_EngagementProfiles>();
            this.I_EngagementStandards = new HashSet<I_EngagementStandards>();
            this.I_EngagementSwots = new HashSet<I_EngagementSwots>();
            this.I_GesCompanies = new HashSet<I_GesCompanies>();
            this.I_RiskCompaniesStatistics = new HashSet<I_RiskCompaniesStatistics>();
            this.I_Scores = new HashSet<I_Scores>();
            this.I_Swots = new HashSet<I_Swots>();
            this.T_Activites = new HashSet<T_Activites>();
            this.G_Organizations = new HashSet<G_Organizations>();
            this.I_NaArticles = new HashSet<I_NaArticles>();
        }
    
        public long I_Companies_Id { get; set; }
        public Nullable<long> MasterI_Companies_Id { get; set; }
        public Nullable<System.Guid> C_C_Companies_Id { get; set; }
        public Nullable<int> C_GesCompanyNr { get; set; }
        public Nullable<long> G_Organizations_Id { get; set; }
        public string Sedol { get; set; }
        public string Isin { get; set; }
        public string IssuerName { get; set; }
        public string SecurityDescription { get; set; }
        public string InformationSource { get; set; }
        public Nullable<long> CountryIncG_Countries_Id { get; set; }
        public Nullable<long> CountryRegG_Countries_Id { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<long> I_SecurityStatuses_Id { get; set; }
        public Nullable<long> I_SecurityEvents_Id { get; set; }
        public Nullable<long> I_SecurityTypes_Id { get; set; }
        public string NameCoalesce { get; set; }
        public string MsciName { get; set; }
        public string FtseName { get; set; }
        public string SixName { get; set; }
        public string OtherName { get; set; }
        public string OldName { get; set; }
        public string MediaName { get; set; }
        public Nullable<long> I_Msci_Id { get; set; }
        public Nullable<long> I_MsciSectors_Id { get; set; }
        public Nullable<long> I_MsciIndustryGroups_Id { get; set; }
        public Nullable<long> I_MsciIndustries_Id { get; set; }
        public Nullable<long> I_MsciSubIndustries_Id { get; set; }
        public Nullable<long> I_Ftse_Id { get; set; }
        public Nullable<long> I_FtseGroups_Id { get; set; }
        public Nullable<long> I_FtseSectors_Id { get; set; }
        public Nullable<long> I_FtseSubSectors_Id { get; set; }
        public string ListSource { get; set; }
        public string WebsiteUrl { get; set; }
        public string VerifiedWebsiteUrl { get; set; }
        public Nullable<System.DateTime> VerifiedWebsiteUrlDate { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DescriptionModified { get; set; }
        public Nullable<long> DescriptionsModifiedByG_Users_Id { get; set; }
        public Nullable<bool> ApprovedGesCompany { get; set; }
        public Nullable<long> I_CompaniesImport_Id { get; set; }
        public Nullable<long> I_PortfolioCompaniesImport_Id { get; set; }
        public bool ShowInClient { get; set; }
        public bool IsGlobalCompactMember { get; set; }
        public Nullable<bool> Gri { get; set; }
        public string MostMaterialRisk { get; set; }
        public string TransparencyDisclosure { get; set; }
        public Nullable<System.DateTime> LastCrawled { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
        public string BbgID { get; set; }
        public string OldBloombergTicker { get; set; }
        public Nullable<decimal> MarketCap { get; set; }
        public string UnGlobalCompact { get; set; }
        public string GriAlignedDisclosure { get; set; }
        public int Id { get; set; }
        public System.Guid InternalId { get; set; }
        public string Name { get; set; }
        public string ExchangeTicker { get; set; }
        public Nullable<System.Guid> CountryOfIncorporationId { get; set; }
        public Nullable<int> SubPeerGroupId { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> IsParkedForGssResearchSince { get; set; }
    
        public virtual Countries Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ManagedDocuments> G_ManagedDocuments { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual G_Users G_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesG_Services> I_CompaniesG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompanies> I_RiskCompanies { get; set; }
        public virtual SubPeerGroups SubPeerGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Companies> I_Companies1 { get; set; }
        public virtual I_Companies I_Companies2 { get; set; }
        public virtual I_FtseGroups I_FtseGroups { get; set; }
        public virtual I_FtseSectors I_FtseSectors { get; set; }
        public virtual I_FtseSubSectors I_FtseSubSectors { get; set; }
        public virtual I_MsciIndustries I_MsciIndustries { get; set; }
        public virtual I_MsciIndustries I_MsciIndustries1 { get; set; }
        public virtual I_MsciIndustryGroups I_MsciIndustryGroups { get; set; }
        public virtual I_MsciIndustryGroups I_MsciIndustryGroups1 { get; set; }
        public virtual I_MsciSectors I_MsciSectors { get; set; }
        public virtual I_MsciSubIndustries I_MsciSubIndustries { get; set; }
        public virtual I_MsciSubIndustries I_MsciSubIndustries1 { get; set; }
        public virtual I_SecurityEvents I_SecurityEvents { get; set; }
        public virtual I_SecurityStatuses I_SecurityStatuses { get; set; }
        public virtual I_SecurityTypes I_SecurityTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesI_CompanyListTypes> I_CompaniesI_CompanyListTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesI_ManagementSystems> I_CompaniesI_ManagementSystems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementDiscussionPoints> I_EngagementDiscussionPoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementGap> I_EngagementGap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementGoal> I_EngagementGoal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementIssuesInfo> I_EngagementIssuesInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementOtherStakeholderViews> I_EngagementOtherStakeholderViews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementProfiles> I_EngagementProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementStandards> I_EngagementStandards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementSwots> I_EngagementSwots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCompanies> I_GesCompanies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RiskCompaniesStatistics> I_RiskCompaniesStatistics { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Scores> I_Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Swots> I_Swots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Activites> T_Activites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Organizations> G_Organizations { get; set; }
        public virtual G_Organizations G_Organizations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_NaArticles> I_NaArticles { get; set; }
    }
}
