//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialCompaniesI_ControversialActivites
    {
        public long I_ControversialCompaniesI_ControversialActivites_Id { get; set; }
        public long I_ControversialCompanies_Id { get; set; }
        public long I_ControversialActivites_Id { get; set; }
        public bool IsObservation { get; set; }
        public Nullable<decimal> InvolvmentStartRange { get; set; }
        public Nullable<decimal> InvolvmentEndRange { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> Screened { get; set; }
        public Nullable<long> SourceG_ManagedDocuments_Id { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual I_ControversialActivites I_ControversialActivites { get; set; }
        public virtual I_ControversialCompanies I_ControversialCompanies { get; set; }
    }
}
