//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialActivites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_ControversialActivites()
        {
            this.I_ControversialComments = new HashSet<I_ControversialComments>();
            this.I_ControversialCompaniesI_ControversialActivites = new HashSet<I_ControversialCompaniesI_ControversialActivites>();
            this.I_PortfoliosG_OrganizationsI_ControversialActivites = new HashSet<I_PortfoliosG_OrganizationsI_ControversialActivites>();
            this.I_ControversialActivitesPresetsItems = new HashSet<I_ControversialActivitesPresetsItems>();
        }
    
        public long I_ControversialActivites_Id { get; set; }
        public Nullable<long> I_ControversialActivitesGroups_Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<long> I_NormAreas_Id { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public bool ShowInOverviewExcelExport { get; set; }
    
        public virtual I_NormAreas I_NormAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialComments> I_ControversialComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialCompaniesI_ControversialActivites> I_ControversialCompaniesI_ControversialActivites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfoliosG_OrganizationsI_ControversialActivites> I_PortfoliosG_OrganizationsI_ControversialActivites { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ControversialActivitesPresetsItems> I_ControversialActivitesPresetsItems { get; set; }
    }
}
