//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_CountryRisk
    {
        public long I_CountryRisk_Id { get; set; }
        public long G_Countries_Id { get; set; }
        public Nullable<short> PeaceAndSecurityScore { get; set; }
        public Nullable<short> RightsAndDemocracyScore { get; set; }
        public Nullable<short> CorruptionScore { get; set; }
        public Nullable<short> EnvironmentScore { get; set; }
        public System.DateTime Created { get; set; }
    }
}
