//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ControversialActivitesPresetsItems
    {
        public long I_ControversialActivitesPresetsItems_Id { get; set; }
        public long I_ControversialActivitesPresets_Id { get; set; }
        public long I_ControversialActivites_Id { get; set; }
        public short MinimumInvolvment { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual I_ControversialActivites I_ControversialActivites { get; set; }
        public virtual I_ControversialActivitesPresets I_ControversialActivitesPresets { get; set; }
    }
}
