//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_EngagementTypes_GesDocument
    {
        public System.Guid Id { get; set; }
        public Nullable<long> EngagementTypeId { get; set; }
        public Nullable<System.Guid> DocumentId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.Guid> DocumentTypeId { get; set; }
    
        public virtual GesDocument GesDocument { get; set; }
        public virtual GesDocTypes GesDocTypes { get; set; }
        public virtual I_EngagementTypes I_EngagementTypes { get; set; }
    }
}
