//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_EngagementTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_EngagementTypes()
        {
            this.GesCaseProfileTemplates = new HashSet<GesCaseProfileTemplates>();
            this.I_EngagementTypes_GesDocument = new HashSet<I_EngagementTypes_GesDocument>();
        }
    
        public long I_EngagementTypes_Id { get; set; }
        public long I_EngagementTypeCategories_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Goal { get; set; }
        public string NextStep { get; set; }
        public string LatestNews { get; set; }
        public string OtherInitiatives { get; set; }
        public string Sources { get; set; }
        public string GesReports { get; set; }
        public Nullable<long> ContactG_Users_Id { get; set; }
        public string Participants { get; set; }
        public string NonSubscriberInformation { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public System.DateTime Created { get; set; }
        public string ThemeImage { get; set; }
        public Nullable<bool> Deactive { get; set; }
        public Nullable<bool> IsShowInClientMenu { get; set; }
        public Nullable<bool> IsShowInCaseProfileTemplate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCaseProfileTemplates> GesCaseProfileTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_EngagementTypes_GesDocument> I_EngagementTypes_GesDocument { get; set; }
    }
}
