//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_EngagementTypeNews
    {
        public long I_EngagementTypeNews_Id { get; set; }
        public long I_EngagementTypes_Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
    }
}
