//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesCaseReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_GesCaseReports()
        {
            this.GesCaseReportSdg = new HashSet<GesCaseReportSdg>();
            this.GesCaseReportSignUp = new HashSet<GesCaseReportSignUp>();
            this.GesUNGPAssessmentForm = new HashSet<GesUNGPAssessmentForm>();
            this.I_ActivityForms = new HashSet<I_ActivityForms>();
            this.I_GesAssociatedCorporations = new HashSet<I_GesAssociatedCorporations>();
            this.I_GesCaseReportReferences = new HashSet<I_GesCaseReportReferences>();
            this.I_GesCaseReportsG_ManagedDocuments = new HashSet<I_GesCaseReportsG_ManagedDocuments>();
            this.I_RelatedCases = new HashSet<I_RelatedCases>();
            this.I_RelatedCases1 = new HashSet<I_RelatedCases>();
            this.I_GesCaseReportsExtra = new HashSet<I_GesCaseReportsExtra>();
            this.I_GesCaseReportsG_Individuals = new HashSet<I_GesCaseReportsG_Individuals>();
            this.I_GesCaseReportsI_Conventions = new HashSet<I_GesCaseReportsI_Conventions>();
            this.I_GesCaseReportsI_GesAssociatedCorporations = new HashSet<I_GesCaseReportsI_GesAssociatedCorporations>();
            this.I_GesCaseReportsI_GesRevisionTexts = new HashSet<I_GesCaseReportsI_GesRevisionTexts>();
            this.I_GesCaseReportSources = new HashSet<I_GesCaseReportSources>();
            this.I_GesCaseReportsI_Norms = new HashSet<I_GesCaseReportsI_Norms>();
            this.I_GesCaseReportSupplementaryReading = new HashSet<I_GesCaseReportSupplementaryReading>();
            this.I_GesCaseReportUpdates = new HashSet<I_GesCaseReportUpdates>();
            this.I_GesCommentary = new HashSet<I_GesCommentary>();
            this.I_GesCompanyDialogues = new HashSet<I_GesCompanyDialogues>();
            this.I_GesLatestNews = new HashSet<I_GesLatestNews>();
            this.I_GesSourceDialogues = new HashSet<I_GesSourceDialogues>();
            this.I_GSSLink = new HashSet<I_GSSLink>();
            this.I_Milestones = new HashSet<I_Milestones>();
        }
    
        public long I_GesCaseReports_Id { get; set; }
        public Nullable<long> OriginalI_GesCaseReports_Id { get; set; }
        public long I_GesCompanies_Id { get; set; }
        public Nullable<long> AnalystG_Users_Id { get; set; }
        public string ReportIncident { get; set; }
        public Nullable<System.DateTime> ReportIncidentModified { get; set; }
        public Nullable<long> I_GesCaseReportStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_GesCaseReportStatuses_IdReviewed { get; set; }
        public Nullable<long> NewI_GesCaseReportStatuses_Id { get; set; }
        public Nullable<System.DateTime> NewI_GesCaseReportStatuses_IdReviewed { get; set; }
        public Nullable<System.DateTime> NewI_GesCaseReportStatuses_IdModified { get; set; }
        public long LocationG_Countries_Id { get; set; }
        public Nullable<System.DateTime> LocationG_Countries_IdModified { get; set; }
        public Nullable<long> Location2G_Countries_Id { get; set; }
        public Nullable<long> Location3G_Countries_Id { get; set; }
        public Nullable<long> Location4G_Countries_Id { get; set; }
        public Nullable<long> Location5G_Countries_Id { get; set; }
        public Nullable<long> I_NaArticles_Id { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> SummaryReviewed { get; set; }
        public Nullable<System.DateTime> SummaryModified { get; set; }
        public string NewSummary { get; set; }
        public string GesComment { get; set; }
        public Nullable<System.DateTime> GesCommentReviewed { get; set; }
        public Nullable<System.DateTime> GesCommentModified { get; set; }
        public Nullable<long> EditI_GesCaseReportStatuses_Id { get; set; }
        public string EditText { get; set; }
        public string Description { get; set; }
        public string DescriptionNew { get; set; }
        public string Conclusion { get; set; }
        public Nullable<System.DateTime> ConclusionReviewed { get; set; }
        public string ConclusionNew { get; set; }
        public string ConclusionObs { get; set; }
        public string Recommendation { get; set; }
        public string RecommendationExludeEf { get; set; }
        public string Revision { get; set; }
        public string SourceDialogueSummary { get; set; }
        public string SourceDialogueNew { get; set; }
        public bool Confirmed { get; set; }
        public Nullable<long> I_GesCaseReportSourceTypes_Id { get; set; }
        public string CompanyDialogueSummary { get; set; }
        public Nullable<System.DateTime> CompanyDialogueSummaryReviewed { get; set; }
        public string CompanyDialogueNew { get; set; }
        public Nullable<System.DateTime> CompanyDialogueNewReviewed { get; set; }
        public string CompanyDialogueSummaryObs { get; set; }
        public string EngagementSummaryClientReport { get; set; }
        public bool ShowInClient { get; set; }
        public Nullable<bool> FeatureInClient { get; set; }
        public Nullable<long> I_GesCaseReportsI_ProcessStatuses_Id { get; set; }
        public string ProcessGoal { get; set; }
        public Nullable<System.DateTime> ProcessGoalReviewed { get; set; }
        public Nullable<System.DateTime> ProcessGoalModified { get; set; }
        public string ProcessStep { get; set; }
        public Nullable<System.DateTime> ProcessStepReviewed { get; set; }
        public Nullable<System.DateTime> ProcessStepUpdated { get; set; }
        public Nullable<long> G_ForumMessages_Id { get; set; }
        public Nullable<long> I_ResponseStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_ResponseStatuses_IdReviewed { get; set; }
        public Nullable<long> I_ProgressStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_ProgressStatuses_IdReviewed { get; set; }
        public Nullable<long> I_NormAreas_Id { get; set; }
        public Nullable<long> FullReportG_ManagedDocuments_Id { get; set; }
        public string LatestNews { get; set; }
        public Nullable<System.DateTime> LatestNewsModified { get; set; }
        public string Comment { get; set; }
        public bool IsBurmaEngCase { get; set; }
        public Nullable<long> I_BurmaRecommendations_Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public bool EngagementTypeIncident { get; set; }
        public bool EngagementTypeCompany { get; set; }
        public bool EngagementTypeHighRiskZone { get; set; }
        public Nullable<long> EngagementTypeI_HighRiskZones_Id { get; set; }
        public bool EngagementTypeThematic { get; set; }
        public Nullable<long> EngagementTypeI_Themes_Id { get; set; }
        public bool EngagementTypeSector { get; set; }
        public Nullable<long> EngagementTypeI_Msci_Id { get; set; }
        public string SuccessStory { get; set; }
        public string IncidentAnalysisSummary { get; set; }
        public string IncidentAnalysisDialogueAndAnalysis { get; set; }
        public string IncidentAnalysisConclusion { get; set; }
        public string IncidentAnalysisGuidelines { get; set; }
        public string IncidentAnalysisSources { get; set; }
        public bool SendNotifications { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
        public string ClosingIncidentAnalysisSummary { get; set; }
        public string ClosingIncidentAnalysisDialogueAndAnalysis { get; set; }
        public string ClosingIncidentAnalysisConclusion { get; set; }
        public Nullable<System.DateTime> ConclusionChanged { get; set; }
        public string Guidelines { get; set; }
        public string CompanyPreparedness { get; set; }
        public string GAPAnalysis { get; set; }
        public string PositiveDevelopment { get; set; }
        public Nullable<System.Guid> CountryId { get; set; }
        public Nullable<long> IssueHeadingId { get; set; }
    
        public virtual Countries Countries { get; set; }
        public virtual G_ForumMessages G_ForumMessages { get; set; }
        public virtual G_ManagedDocuments G_ManagedDocuments { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual G_Users G_Users1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCaseReportSdg> GesCaseReportSdg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesCaseReportSignUp> GesCaseReportSignUp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GesUNGPAssessmentForm> GesUNGPAssessmentForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_ActivityForms> I_ActivityForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesAssociatedCorporations> I_GesAssociatedCorporations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportReferences> I_GesCaseReportReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsG_ManagedDocuments> I_GesCaseReportsG_ManagedDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RelatedCases> I_RelatedCases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_RelatedCases> I_RelatedCases1 { get; set; }
        public virtual I_GesCaseReportsI_ProcessStatuses I_GesCaseReportsI_ProcessStatuses { get; set; }
        public virtual I_GesCaseReportSourceTypes I_GesCaseReportSourceTypes { get; set; }
        public virtual I_GesCaseReportStatuses I_GesCaseReportStatuses { get; set; }
        public virtual I_GesCaseReportStatuses I_GesCaseReportStatuses1 { get; set; }
        public virtual I_GesCaseReportStatuses I_GesCaseReportStatuses2 { get; set; }
        public virtual I_GesCompanies I_GesCompanies { get; set; }
        public virtual I_NaArticles I_NaArticles { get; set; }
        public virtual IssueHeading IssueHeading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsExtra> I_GesCaseReportsExtra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsG_Individuals> I_GesCaseReportsG_Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_Conventions> I_GesCaseReportsI_Conventions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_GesAssociatedCorporations> I_GesCaseReportsI_GesAssociatedCorporations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_GesRevisionTexts> I_GesCaseReportsI_GesRevisionTexts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportSources> I_GesCaseReportSources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_Norms> I_GesCaseReportsI_Norms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportSupplementaryReading> I_GesCaseReportSupplementaryReading { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportUpdates> I_GesCaseReportUpdates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCommentary> I_GesCommentary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCompanyDialogues> I_GesCompanyDialogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesLatestNews> I_GesLatestNews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesSourceDialogues> I_GesSourceDialogues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GSSLink> I_GSSLink { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Milestones> I_Milestones { get; set; }
    }
}
