//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesCaseReportsI_GesRevisionTexts
    {
        public long I_GesCaseReportsI_GesRevisionTexts_Id { get; set; }
        public long I_GesCaseReports_Id { get; set; }
        public long I_GesRevisionTexts_Id { get; set; }
        public bool Checked { get; set; }
        public string DateText { get; set; }
        public string Description { get; set; }
    
        public virtual I_GesRevisionTexts I_GesRevisionTexts { get; set; }
        public virtual I_GesCaseReports I_GesCaseReports { get; set; }
    }
}
