//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesCaseReportHistory
    {
        public long I_GesCaseReportHistory_Id { get; set; }
        public long I_GesCaseReports_Id { get; set; }
        public Nullable<long> I_ResponseStatuses_Id { get; set; }
        public Nullable<long> I_ProgressStatuses_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual I_ProgressStatuses I_ProgressStatuses { get; set; }
        public virtual I_ResponseStatuses I_ResponseStatuses { get; set; }
    }
}
