//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesAssociatedCorporations
    {
        public long I_GesAssociatedCorporations_Id { get; set; }
        public Nullable<long> I_GesCaseReports_Id { get; set; }
        public string Name { get; set; }
        public string Ownership { get; set; }
        public string Comment { get; set; }
        public bool Traded { get; set; }
        public long ShowInReport { get; set; }
    
        public virtual I_GesCaseReports I_GesCaseReports { get; set; }
    }
}
