//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesCompanies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_GesCompanies()
        {
            this.I_GesCompanyWatcher = new HashSet<I_GesCompanyWatcher>();
            this.I_GesCaseReports = new HashSet<I_GesCaseReports>();
        }
    
        public long I_GesCompanies_Id { get; set; }
        public long I_Companies_Id { get; set; }
        public string Comment { get; set; }
        public string EngagementAction { get; set; }
        public string EngagementChallenge { get; set; }
        public string EngagementResponse { get; set; }
        public string EngagementProgress { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCompanyWatcher> I_GesCompanyWatcher { get; set; }
        public virtual I_Companies I_Companies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReports> I_GesCaseReports { get; set; }
    }
}
