//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_GesCaseReports_Audit
    {
        public Nullable<long> I_GesCaseReports_Id { get; set; }
        public Nullable<long> OriginalI_GesCaseReports_Id { get; set; }
        public long I_GesCompanies_Id { get; set; }
        public Nullable<long> AnalystG_Users_Id { get; set; }
        public string ReportIncident { get; set; }
        public Nullable<System.DateTime> ReportIncidentModified { get; set; }
        public Nullable<long> I_GesCaseReportStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_GesCaseReportStatuses_IdReviewed { get; set; }
        public Nullable<long> NewI_GesCaseReportStatuses_Id { get; set; }
        public Nullable<System.DateTime> NewI_GesCaseReportStatuses_IdReviewed { get; set; }
        public Nullable<System.DateTime> NewI_GesCaseReportStatuses_IdModified { get; set; }
        public long LocationG_Countries_Id { get; set; }
        public Nullable<System.DateTime> LocationG_Countries_IdModified { get; set; }
        public Nullable<long> Location2G_Countries_Id { get; set; }
        public Nullable<long> Location3G_Countries_Id { get; set; }
        public Nullable<long> Location4G_Countries_Id { get; set; }
        public Nullable<long> Location5G_Countries_Id { get; set; }
        public Nullable<long> I_NaArticles_Id { get; set; }
        public string Summary { get; set; }
        public Nullable<System.DateTime> SummaryReviewed { get; set; }
        public Nullable<System.DateTime> SummaryModified { get; set; }
        public string NewSummary { get; set; }
        public string GesComment { get; set; }
        public Nullable<System.DateTime> GesCommentReviewed { get; set; }
        public Nullable<System.DateTime> GesCommentModified { get; set; }
        public Nullable<long> EditI_GesCaseReportStatuses_Id { get; set; }
        public string EditText { get; set; }
        public string Description { get; set; }
        public string DescriptionNew { get; set; }
        public string Conclusion { get; set; }
        public Nullable<System.DateTime> ConclusionReviewed { get; set; }
        public string ConclusionNew { get; set; }
        public string ConclusionObs { get; set; }
        public string Recommendation { get; set; }
        public string RecommendationExludeEf { get; set; }
        public string Revision { get; set; }
        public string SourceDialogueSummary { get; set; }
        public string SourceDialogueNew { get; set; }
        public string Confirmed { get; set; }
        public Nullable<long> I_GesCaseReportSourceTypes_Id { get; set; }
        public string CompanyDialogueSummary { get; set; }
        public Nullable<System.DateTime> CompanyDialogueSummaryReviewed { get; set; }
        public string CompanyDialogueNew { get; set; }
        public Nullable<System.DateTime> CompanyDialogueNewReviewed { get; set; }
        public string CompanyDialogueSummaryObs { get; set; }
        public string EngagementSummaryClientReport { get; set; }
        public bool ShowInClient { get; set; }
        public Nullable<bool> FeatureInClient { get; set; }
        public Nullable<long> I_GesCaseReportsI_ProcessStatuses_Id { get; set; }
        public string ProcessGoal { get; set; }
        public Nullable<System.DateTime> ProcessGoalReviewed { get; set; }
        public Nullable<System.DateTime> ProcessGoalModified { get; set; }
        public string ProcessStep { get; set; }
        public Nullable<System.DateTime> ProcessStepReviewed { get; set; }
        public Nullable<System.DateTime> ProcessStepUpdated { get; set; }
        public Nullable<long> G_ForumMessages_Id { get; set; }
        public Nullable<long> I_ResponseStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_ResponseStatuses_IdReviewed { get; set; }
        public Nullable<long> I_ProgressStatuses_Id { get; set; }
        public Nullable<System.DateTime> I_ProgressStatuses_IdReviewed { get; set; }
        public Nullable<long> I_NormAreas_Id { get; set; }
        public Nullable<long> FullReportG_ManagedDocuments_Id { get; set; }
        public string LatestNews { get; set; }
        public Nullable<System.DateTime> LatestNewsModified { get; set; }
        public string Comment { get; set; }
        public bool IsBurmaEngCase { get; set; }
        public Nullable<long> I_BurmaRecommendations_Id { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public bool EngagementTypeIncident { get; set; }
        public bool EngagementTypeCompany { get; set; }
        public bool EngagementTypeHighRiskZone { get; set; }
        public Nullable<long> EngagementTypeI_HighRiskZones_Id { get; set; }
        public bool EngagementTypeThematic { get; set; }
        public Nullable<long> EngagementTypeI_Themes_Id { get; set; }
        public bool EngagementTypeSector { get; set; }
        public Nullable<long> EngagementTypeI_Msci_Id { get; set; }
        public string SuccessStory { get; set; }
        public string IncidentAnalysisSummary { get; set; }
        public string IncidentAnalysisDialogueAndAnalysis { get; set; }
        public string IncidentAnalysisConclusion { get; set; }
        public string IncidentAnalysisGuidelines { get; set; }
        public string IncidentAnalysisSources { get; set; }
        public bool SendNotifications { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
        public string ClosingIncidentAnalysisSummary { get; set; }
        public string ClosingIncidentAnalysisDialogueAndAnalysis { get; set; }
        public string ClosingIncidentAnalysisConclusion { get; set; }
        public Nullable<System.DateTime> ConclusionChanged { get; set; }
        public string AuditDataState { get; set; }
        public string AuditDMLAction { get; set; }
        public string AuditChangedColumns { get; set; }
        public string AuditUser { get; set; }
        public Nullable<System.DateTime> AuditDateTime { get; set; }
        public string TransactionId { get; set; }
    }
}
