//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_IndividualListsG_Individuals
    {
        public long I_IndividualListsG_Individuals_Id { get; set; }
        public long I_IndividualLists_Id { get; set; }
        public long G_Individuals_Id { get; set; }
        public Nullable<long> I_Msci_Id { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
    
        public virtual G_Individuals G_Individuals { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual I_IndividualLists I_IndividualLists { get; set; }
    }
}
