//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_IndividualLists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_IndividualLists()
        {
            this.I_IndividualListsG_Individuals = new HashSet<I_IndividualListsG_Individuals>();
            this.I_NasI_IndividualLists = new HashSet<I_NasI_IndividualLists>();
            this.M_MessagesI_IndividualLists = new HashSet<M_MessagesI_IndividualLists>();
        }
    
        public long I_IndividualLists_Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_IndividualListsG_Individuals> I_IndividualListsG_Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_NasI_IndividualLists> I_NasI_IndividualLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MessagesI_IndividualLists> M_MessagesI_IndividualLists { get; set; }
    }
}
