//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ManagementSystems
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_ManagementSystems()
        {
            this.I_CompaniesI_ManagementSystems = new HashSet<I_CompaniesI_ManagementSystems>();
        }
    
        public long I_ManagementSystems_Id { get; set; }
        public long I_ManagementSystemTypes_Id { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Type { get; set; }
        public string Background { get; set; }
        public string Guidelines { get; set; }
        public string Objective { get; set; }
        public string Administration { get; set; }
        public string Conventions { get; set; }
        public string Links { get; set; }
        public string Implementation { get; set; }
        public Nullable<long> I_NormAreas_Id1 { get; set; }
        public Nullable<long> I_NormAreas_Id2 { get; set; }
        public Nullable<long> I_NormAreas_Id3 { get; set; }
        public Nullable<long> I_NormAreas_Id4 { get; set; }
        public Nullable<long> I_NormAreas_Id5 { get; set; }
        public Nullable<long> I_NormAreas_Id6 { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_CompaniesI_ManagementSystems> I_CompaniesI_ManagementSystems { get; set; }
        public virtual I_ManagementSystemTypes I_ManagementSystemTypes { get; set; }
    }
}
