//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Msci_Tree
    {
        public long I_Msci_Tree_Id { get; set; }
        public Nullable<long> ParentI_Msci_Tree_Id { get; set; }
        public long I_Msci_Id { get; set; }
        public Nullable<byte> Depth { get; set; }
        public string Lineage { get; set; }
    }
}
