//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Nas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Nas()
        {
            this.I_NasI_IndividualLists = new HashSet<I_NasI_IndividualLists>();
            this.I_NasI_NaArticles = new HashSet<I_NasI_NaArticles>();
        }
    
        public long I_Nas_Id { get; set; }
        public string PrefixText { get; set; }
        public string SuffixText { get; set; }
        public bool Extended { get; set; }
        public bool ShowInCsc { get; set; }
        public Nullable<System.DateTime> DateRangeStart { get; set; }
        public Nullable<System.DateTime> DateRangeEnd { get; set; }
        public Nullable<System.DateTime> DateSent { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_Users G_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_NasI_IndividualLists> I_NasI_IndividualLists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_NasI_NaArticles> I_NasI_NaArticles { get; set; }
    }
}
