//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_NasI_NaArticles
    {
        public long I_NasI_NaArticles_Id { get; set; }
        public long I_Nas_Id { get; set; }
        public long I_NaArticles_Id { get; set; }
    
        public virtual I_Nas I_Nas { get; set; }
        public virtual I_NaArticles I_NaArticles { get; set; }
    }
}
