//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Norms
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Norms()
        {
            this.I_GesCaseReportsI_Norms = new HashSet<I_GesCaseReportsI_Norms>();
        }
    
        public long I_Norms_Id { get; set; }
        public Nullable<long> I_NormCategories_Id { get; set; }
        public string GesCode { get; set; }
        public string Code { get; set; }
        public string Source { get; set; }
        public string SourceShort { get; set; }
        public string SiriNormArea { get; set; }
        public string SectionTitle { get; set; }
        public string SectionText { get; set; }
        public string SectionNr { get; set; }
        public string SectionArea { get; set; }
        public string FriendlyName { get; set; }
        public string PNr { get; set; }
        public string Text { get; set; }
        public string Url { get; set; }
        public string FullText { get; set; }
        public bool Active { get; set; }
        public bool Sweden { get; set; }
        public Nullable<int> ExternalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_GesCaseReportsI_Norms> I_GesCaseReportsI_Norms { get; set; }
        public virtual I_NormCategories I_NormCategories { get; set; }
    }
}
