//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_PdfExportSettings
    {
        public string UserPassword { get; set; }
        public string OwnerPassword { get; set; }
        public bool AllowAssembly { get; set; }
        public bool AllowCopy { get; set; }
        public bool AllowDegradedPrinting { get; set; }
        public bool AllowFillIn { get; set; }
        public bool AllowModifyAnnotations { get; set; }
        public bool AllowModifyContents { get; set; }
        public bool AllowPrinting { get; set; }
        public bool AllowScreenReaders { get; set; }
    }
}
