//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_PortfoliosG_Organizations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_PortfoliosG_Organizations()
        {
            this.I_PortfoliosG_OrganizationsG_Services = new HashSet<I_PortfoliosG_OrganizationsG_Services>();
            this.I_PortfoliosG_OrganizationsI_ControversialActivites = new HashSet<I_PortfoliosG_OrganizationsI_ControversialActivites>();
        }
    
        public long I_PortfoliosG_Organizations_Id { get; set; }
        public long I_Portfolios_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public bool IncludeInAlerts { get; set; }
        public string IfStatus { get; set; }
        public Nullable<long> IfI_ProgressStatuses_Id { get; set; }
        public string I_AlertRatings_Id { get; set; }
        public bool ShowInCsc { get; set; }
    
        public virtual I_Portfolios I_Portfolios { get; set; }
        public virtual I_ProgressStatuses I_ProgressStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfoliosG_OrganizationsG_Services> I_PortfoliosG_OrganizationsG_Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_PortfoliosG_OrganizationsI_ControversialActivites> I_PortfoliosG_OrganizationsI_ControversialActivites { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
