//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ProcessStatuses
    {
        public long I_ProcessStatuses_Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string BurmaName { get; set; }
        public Nullable<long> G_ReportingTemplates_Id { get; set; }
        public Nullable<long> G_ReportingPageModules_Id { get; set; }
        public Nullable<int> SortOrder { get; set; }
    
        public virtual G_ReportingPageModules G_ReportingPageModules { get; set; }
        public virtual G_ReportingTemplates G_ReportingTemplates { get; set; }
    }
}
