//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_ProxyResolutions
    {
        public long I_ProxyResolutions_Id { get; set; }
        public Nullable<long> I_CalenderEvents_Id { get; set; }
        public string ResolutionName { get; set; }
        public string ResolutionType { get; set; }
        public Nullable<bool> ShareholderResolution { get; set; }
        public string ManagementRecommendation { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> ltipRelated { get; set; }
        public string Resolution { get; set; }
        public System.DateTime Created { get; set; }
    }
}
