//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Questions()
        {
            this.I_Answers = new HashSet<I_Answers>();
            this.I_MsciI_Questions = new HashSet<I_MsciI_Questions>();
            this.I_Scores = new HashSet<I_Scores>();
            this.I_QuestionsByRisk = new HashSet<I_QuestionsByRisk>();
        }
    
        public long I_Questions_Id { get; set; }
        public Nullable<long> I_Sections_Id { get; set; }
        public string ShortName { get; set; }
        public string ShortNamePl { get; set; }
        public string Text { get; set; }
        public string TextPl { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
    
        public virtual G_Users G_Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Answers> I_Answers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_MsciI_Questions> I_MsciI_Questions { get; set; }
        public virtual I_Sections I_Sections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Scores> I_Scores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_QuestionsByRisk> I_QuestionsByRisk { get; set; }
    }
}
