//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_RatingsConversionTable
    {
        public long I_RatingsConversionTable_Id { get; set; }
        public decimal RangeStart { get; set; }
        public decimal RangeEnd { get; set; }
        public long I_CharScores_Id { get; set; }
    }
}
