//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_RelatedCases
    {
        public long ID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> Issue_ID { get; set; }
        public Nullable<long> Related_ID { get; set; }
    
        public virtual I_GesCaseReports I_GesCaseReports { get; set; }
        public virtual I_GesCaseReports I_GesCaseReports1 { get; set; }
    }
}
