//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_RiskCompanies
    {
        public long I_RiskCompanies_Id { get; set; }
        public long I_Companies_Id { get; set; }
        public Nullable<System.DateTime> EnvSourceSiri { get; set; }
        public string EnvSourceAnnual { get; set; }
        public Nullable<System.DateTime> EnvSourceSocrates { get; set; }
        public Nullable<System.DateTime> EnvSourceWebsite { get; set; }
        public string EnvSourceOther { get; set; }
        public string EnvSourceOther2 { get; set; }
        public string EnvSourceOther3 { get; set; }
        public string EnvContactEmail { get; set; }
        public string EnvContactPhone { get; set; }
        public Nullable<long> EnvContactG_Individuals_Id { get; set; }
        public Nullable<System.DateTime> EnvAnalysisDate { get; set; }
        public Nullable<System.DateTime> EnvClimateChangeAnalysisDate { get; set; }
        public Nullable<System.DateTime> EnvWaterAnalysisDate { get; set; }
        public Nullable<long> EnvAnalystG_Users_Id { get; set; }
        public string EnvGeneralComments { get; set; }
        public Nullable<long> EnvGeneralRiskI_CharScores_Id { get; set; }
        public string HROldSource { get; set; }
        public Nullable<System.DateTime> HrSourceSiri { get; set; }
        public string HrSourceAnnual { get; set; }
        public Nullable<System.DateTime> HrSourceSocrates { get; set; }
        public Nullable<System.DateTime> HrSourceWebsite { get; set; }
        public string HrSourceOther { get; set; }
        public string HrSourceOther2 { get; set; }
        public string HrSourceOther3 { get; set; }
        public string HrContactEmail { get; set; }
        public string HrContactPhone { get; set; }
        public Nullable<long> HrContactG_Individuals_Id { get; set; }
        public Nullable<System.DateTime> HrAnalysisDate { get; set; }
        public Nullable<long> HrAnalystG_Users_Id { get; set; }
        public string HrGeneralComments { get; set; }
        public Nullable<long> HrGeneralRiskI_CharScores_Id { get; set; }
        public Nullable<System.DateTime> CgSourceSiri { get; set; }
        public string CgSourceAnnual { get; set; }
        public Nullable<System.DateTime> CgSourceSocrates { get; set; }
        public Nullable<System.DateTime> CgSourceWebsite { get; set; }
        public string CgSourceOther { get; set; }
        public string CgSourceOther2 { get; set; }
        public string CgSourceOther3 { get; set; }
        public string CgContactEmail { get; set; }
        public string CgContactPhone { get; set; }
        public Nullable<long> CgContactG_Individuals_Id { get; set; }
        public Nullable<System.DateTime> CgAnalysisDate { get; set; }
        public Nullable<long> CgAnalystG_Users_Id { get; set; }
        public string CgGeneralComments { get; set; }
        public Nullable<long> CgGeneralRiskI_CharScores_Id { get; set; }
        public Nullable<float> PreparednessRating { get; set; }
        public Nullable<long> PreparednessRatingI_CharScores_Id { get; set; }
        public Nullable<float> PerformanceRating { get; set; }
        public Nullable<long> PerformanceRatingI_CharScores_Id { get; set; }
        public Nullable<float> TotalEnvRating { get; set; }
        public Nullable<long> TotalEnvRatingI_CharScores_Id { get; set; }
        public Nullable<float> EmployeeRating { get; set; }
        public Nullable<long> EmployeeRatingI_CharScores_Id { get; set; }
        public Nullable<float> CommunityRating { get; set; }
        public Nullable<long> CommunityRatingI_CharScores_Id { get; set; }
        public Nullable<float> SupplierRating { get; set; }
        public Nullable<long> SupplierRatingI_CharScores_Id { get; set; }
        public Nullable<float> TotalHrRating { get; set; }
        public Nullable<long> TotalHrRatingI_CharScores_Id { get; set; }
        public Nullable<float> BoardManagementRating { get; set; }
        public Nullable<long> BoardManagementRatingI_CharScores_Id { get; set; }
        public Nullable<float> TransparencyRating { get; set; }
        public Nullable<long> TransparencyRatingI_CharScores_Id { get; set; }
        public Nullable<float> ShareholderRightsRating { get; set; }
        public Nullable<long> ShareholderRightsRatingI_CharScores_Id { get; set; }
        public Nullable<float> TotaCgRating { get; set; }
        public Nullable<long> TotalCgRatingI_CharScores_Id { get; set; }
        public string EnvProfileText { get; set; }
        public string Env360ProfileText { get; set; }
        public string HrProfileText { get; set; }
        public string Hr360ProfileText { get; set; }
        public string CgProfileText { get; set; }
        public string Cg360ProfileText { get; set; }
        public Nullable<System.DateTime> NextAnnualReport { get; set; }
        public Nullable<long> EnvI_InformationQuality_Id { get; set; }
        public Nullable<long> HrI_InformationQuality_Id { get; set; }
        public Nullable<long> CgI_InformationQuality_Id { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
    
        public virtual G_Users G_Users { get; set; }
        public virtual G_Users G_Users1 { get; set; }
        public virtual G_Users G_Users2 { get; set; }
        public virtual I_CharScores I_CharScores { get; set; }
        public virtual I_CharScores I_CharScores1 { get; set; }
        public virtual I_CharScores I_CharScores2 { get; set; }
        public virtual I_CharScores I_CharScores3 { get; set; }
        public virtual I_CharScores I_CharScores4 { get; set; }
        public virtual I_CharScores I_CharScores5 { get; set; }
        public virtual I_CharScores I_CharScores6 { get; set; }
        public virtual I_CharScores I_CharScores7 { get; set; }
        public virtual I_CharScores I_CharScores8 { get; set; }
        public virtual I_InformationQuality I_InformationQuality { get; set; }
        public virtual I_InformationQuality I_InformationQuality1 { get; set; }
        public virtual I_Companies I_Companies { get; set; }
    }
}
