//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Scores
    {
        public long I_Scores_Id { get; set; }
        public Nullable<long> I_Companies_Id { get; set; }
        public long I_Questions_Id { get; set; }
        public bool StandardQuestion { get; set; }
        public Nullable<long> I_Answers_Id { get; set; }
        public string Description { get; set; }
        public string Old360Comment { get; set; }
        public string Comment { get; set; }
        public Nullable<long> PrimaryI_Sources_Id { get; set; }
        public Nullable<long> SecondaryI_Sources_Id { get; set; }
        public Nullable<long> CompanySuggestedI_Answers_Id { get; set; }
        public string CompanyComment { get; set; }
        public string CompanySource { get; set; }
        public string CompanySourceUrl { get; set; }
        public Nullable<long> CompanySourceG_Uploads_Id { get; set; }
        public string AnalystAnswer { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
    
        public virtual G_Uploads G_Uploads { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual I_Answers I_Answers { get; set; }
        public virtual I_Answers I_Answers1 { get; set; }
        public virtual I_Questions I_Questions { get; set; }
        public virtual I_Sources I_Sources { get; set; }
        public virtual I_Companies I_Companies { get; set; }
    }
}
