//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class I_Sections
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public I_Sections()
        {
            this.I_Questions = new HashSet<I_Questions>();
        }
    
        public long I_Sections_Id { get; set; }
        public Nullable<long> I_Categories_Id { get; set; }
        public string Name { get; set; }
        public bool AppliesToAllCompanies { get; set; }
    
        public virtual I_Categories I_Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<I_Questions> I_Questions { get; set; }
    }
}
