//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_MessagesI_IndividualLists
    {
        public long M_MessagesI_IndividualLists_Id { get; set; }
        public long M_Messages_Id { get; set; }
        public long I_IndividualLists_Id { get; set; }
    
        public virtual I_IndividualLists I_IndividualLists { get; set; }
        public virtual M_Messages M_Messages { get; set; }
    }
}
