//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_Messages()
        {
            this.M_MessagesI_IndividualLists = new HashSet<M_MessagesI_IndividualLists>();
        }
    
        public long M_Messages_Id { get; set; }
        public Nullable<long> M_MessageTypes_Id { get; set; }
        public Nullable<long> G_Cultures_Id { get; set; }
        public string From { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public bool IsHtml { get; set; }
        public Nullable<System.DateTime> Sent { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_Cultures G_Cultures { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual M_MessageTypes M_MessageTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_MessagesI_IndividualLists> M_MessagesI_IndividualLists { get; set; }
    }
}
