//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Inboxes
    {
        public long O_Inboxes_Id { get; set; }
        public long O_Groups_Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Created { get; set; }
    }
}
