//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_NewsItemsI_Companies
    {
        public long O_NewsItemsI_Companies_Id { get; set; }
        public long O_NewsItems_Id { get; set; }
        public long I_Companies_Id { get; set; }
        public System.DateTime Created { get; set; }
    }
}
