//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_NewsItemsArchive
    {
        public long O_NewsItems_Id { get; set; }
        public string Heading { get; set; }
        public string Abstract { get; set; }
        public string Url { get; set; }
        public Nullable<long> O_Sources_Id { get; set; }
        public Nullable<long> I_Companies_Id { get; set; }
        public Nullable<long> O_SearchTerms_Id { get; set; }
        public Nullable<long> O_Inboxes_Id { get; set; }
        public Nullable<long> I_NormAreas_Id { get; set; }
        public Nullable<long> O_AnalysisLevels_Id { get; set; }
        public Nullable<long> O_AlertStatuses_Id { get; set; }
        public bool IncludeInNewsletter { get; set; }
        public Nullable<System.DateTime> DatePublishedInNewsletter { get; set; }
        public bool PublishOnPortal { get; set; }
        public bool Removed { get; set; }
        public System.DateTime Created { get; set; }
        public string raw_in_id { get; set; }
        public string AppliedSearchTerm { get; set; }
        public Nullable<int> SearchResultIndex { get; set; }
        public bool CSRemoved { get; set; }
    }
}
