//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Sources
    {
        public long O_Sources_Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public string SearchString { get; set; }
        public Nullable<long> I_Portfolios_Id { get; set; }
        public Nullable<long> O_Inboxes_Id { get; set; }
        public bool IsRss { get; set; }
        public bool Enabled { get; set; }
        public Nullable<System.DateTime> LastCrawled { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual I_Portfolios I_Portfolios { get; set; }
    }
}
