//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class R_Lists
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public R_Lists()
        {
            this.E_MessagesR_Lists = new HashSet<E_MessagesR_Lists>();
            this.R_ListsG_Individuals = new HashSet<R_ListsG_Individuals>();
            this.R_ListsG_Organizations = new HashSet<R_ListsG_Organizations>();
        }
    
        public long R_Lists_Id { get; set; }
        public long G_Organizations_Id { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<E_MessagesR_Lists> E_MessagesR_Lists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ListsG_Individuals> R_ListsG_Individuals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_ListsG_Organizations> R_ListsG_Organizations { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
