//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Activites
    {
        public long T_Activites_Id { get; set; }
        public long G_Individuals_Id { get; set; }
        public Nullable<long> T_Projects_Id { get; set; }
        public Nullable<long> CustomerG_Organizations_Id { get; set; }
        public long T_ActivityTypes_Id { get; set; }
        public Nullable<long> I_Companies_Id { get; set; }
        public Nullable<long> I_Msci_Id { get; set; }
        public System.DateTime ActivityStart { get; set; }
        public System.DateTime ActivityEnd { get; set; }
        public string Comment { get; set; }
        public bool Billable { get; set; }
        public Nullable<long> T_ApprovalStatuses_Id { get; set; }
        public System.DateTime Modified { get; set; }
        public Nullable<long> ModifiedByG_Users_Id { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual G_Individuals G_Individuals { get; set; }
        public virtual G_Users G_Users { get; set; }
        public virtual T_ActivityTypes T_ActivityTypes { get; set; }
        public virtual T_ApprovalStatuses T_ApprovalStatuses { get; set; }
        public virtual T_Projects T_Projects { get; set; }
        public virtual I_Companies I_Companies { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
