//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ActivitesI_GesCaseReports
    {
        public long T_ActivitesI_GesCaseReports_Id { get; set; }
        public long T_Activites_Id { get; set; }
        public long I_GesCaseReports_Id { get; set; }
        public System.DateTime Created { get; set; }
    }
}
