//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ActMan_Start
    {
        public long T_ActMan_Start_Id { get; set; }
        public long G_Individuals_Id { get; set; }
        public System.DateTime StartTime { get; set; }
    }
}
