//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GES.Inside.Data.DataContexts
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Translate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Translate()
        {
            this.T_Translated = new HashSet<T_Translated>();
        }
    
        public long T_Translate_Id { get; set; }
        public Nullable<long> G_Organizations_Id { get; set; }
        public long G_Cultures_Id { get; set; }
        public string ClientReference { get; set; }
        public string ContextLink { get; set; }
        public string PreContext { get; set; }
        public string Text { get; set; }
        public string PostContext { get; set; }
        public string Comment { get; set; }
        public System.DateTime Created { get; set; }
        public bool New { get; set; }
    
        public virtual G_Cultures G_Cultures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Translated> T_Translated { get; set; }
        public virtual G_Organizations G_Organizations { get; set; }
    }
}
