declare @id uniqueidentifier;
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Palm Oil Final Report - February 2018.pdf','Palm Oil Final Report - February 2018.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (14,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Palm Oil Bi-annual Report - April 2017.pdf','Palm Oil Bi-annual Report - April 2017.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (14,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Palm Oil Benchmark Study.pdf','Palm Oil Benchmark Study.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (14,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Palm Oil Benchmark Study.xlsx','Palm Oil Benchmark Study.xlsx',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (14,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'June 2018 Country Risks Brazil.pdf','June 2018 Country Risks Brazil.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '2018 Brief Emerging Markets Engagement description.pdf','2018 Brief Emerging Markets Engagement description.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '20170927 EME and the OECD guidelines.pdf','20170927 EME and the OECD guidelines.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '20180320 EME Webinar 500 meetings - what have we learned.pptx','20180320 EME Webinar 500 meetings - what have we learned.pptx',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'May 2018 Country Risks Philippines.pdf','May 2018 Country Risks Philippines.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'May 2018 Country Risks Thailand.pdf','May 2018 Country Risks Thailand.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (9,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Carbon Risk Engagement Biannual Report_January 2018.pdf','Carbon Risk Engagement Biannual Report_January 2018.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (17,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Carbon Risk Engagement Biannual Report_June 2017.pdf','Carbon Risk Engagement Biannual Report_June 2017.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (17,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Carbon Risk Engagement Biannual Report_December 2016.pdf','Carbon Risk Engagement Biannual Report_December 2016.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (17,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Carbon Risk Engagement Biannual Report_April 2016.pdf','Carbon Risk Engagement Biannual Report_April 2016.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (17,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_February2018.pdf','Update Report_Burma Engagement_February2018.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_July2017.pdf','Update Report_Burma Engagement_July2017.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_February2017_Final.pdf','Update Report_Burma Engagement_February2017_Final.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_July2016.pdf','Update Report_Burma Engagement_July2016.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_February2016.pdf','Update Report_Burma Engagement_February2016.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'GES Burma Engagement Final Report Feb2012-May2015.pdf','GES Burma Engagement Final Report Feb2012-May2015.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_July2014_FINAL.pdf','Update Report_Burma Engagement_July2014_FINAL.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Burma Engagement _Methodology_130705.pdf','Burma Engagement _Methodology_130705.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'GES BURMA POSITION PAPER_130705.pdf','GES BURMA POSITION PAPER_130705.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_Nov 2012.pdf','Update Report_Burma Engagement_Nov 2012.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'GES Burma Benchmark Report_Feb 2012.pdf','GES Burma Benchmark Report_Feb 2012.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Update Report_Burma Engagement_Dec2013.pdf','Update Report_Burma Engagement_Dec2013.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (5,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '150605_Western Sahara_Final report.pdf','150605_Western Sahara_Final report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '141203_Western Sahara_Update report.pdf','141203_Western Sahara_Update report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '140627_Western_Sahara_Update_report.pdf','140627_Western_Sahara_Update_report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '130703_Western_Sahara_Update_report.pdf','130703_Western_Sahara_Update_report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '121109_Western Sahara_Update report.pdf','121109_Western Sahara_Update report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Western Sahara Baseline Report_May 2012.pdf','Western Sahara Baseline Report_May 2012.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '111017_Project Western Sahara_FINALVERSION.pdf','111017_Project Western Sahara_FINALVERSION.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, '131209_Western Sahara_Update report.pdf','131209_Western Sahara_Update report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (4,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Water Engagement_Biannual Report_March 2018.pdf','Water Engagement_Biannual Report_March 2018.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (19,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Water Engagement_Biannual Report_September 2017.pdf','Water Engagement_Biannual Report_September 2017.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (19,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Benchmarking Report March 2017.pdf','Benchmarking Report March 2017.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (19,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Water Stewardship Engagement Baseline Report.pdf','Water Stewardship Engagement Baseline Report.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (19,@id, null);
set @id  = NEWID();
INSERT INTO [dbo].[GesDocument] (DocumentId,[Name],[FileName],GesDocumentServiceId, HashCodeDocument) VALUES(@id, 'Taxation Engagement Bi-annual Report - January 2018.pdf','Taxation Engagement Bi-annual Report - January 2018.pdf',6,'Theme');
INSERT INTO [dbo].[I_EngagementTypes_GesDocument] ([EngagementTypeId],[DocumentId], Created) VALUES (20,@id, null);
