// <auto-generated />
namespace GSS.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddGSS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGSS));
        
        string IMigrationMetadata.Id
        {
            get { return "201907030621105_AddGSS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
